from .cleaning import coerce_str
import re

def _basic_key(x):
    """Rəng adını sabit müqayisə açarına çevirir.
    Məs: 'Qırmızı metallik' -> 'qirmizi metallik'.
    """
    s = (coerce_str(x) or "").strip().lower()
    repl = {
        "ə": "e", "ı": "i", "ö": "o", "ü": "u",
        "ğ": "g", "ş": "s", "ç": "c",
    }
    for a, b in repl.items():
        s = s.replace(a, b)
    s = s.replace("i̇", "i")
    s = re.sub(r"[^a-z0-9]+", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def _strip_descriptors(key):
    """Metallik/metal/sədəf/xətt kimi təsviri sözləri silir.
    Bu, 'Qara metallik' və 'Qara' kimi variantları eyni tanımağa kömək edir.
    """
    s = key or ""
    for word in ["metallik", "metallic", "metalik", "metal", "sedef", "perlam", "xett", "mat"]:
        s = re.sub(rf"\b{word}\b", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

COLOR_MAPPING = {
    'aciq ag': 'Ağ',
    'aciq bej': 'Bej',
    'aciq benovseyi': 'Bənövşəyi',
    'aciq boz': 'Boz',
    'aciq boz mavi': 'Göy',
    'aciq boz metallik': 'Boz',
    'aciq boz yasil': 'Yaşıl',
    'aciq boz yasil metallik': 'Yaşıl',
    'aciq goy': 'Göy',
    'aciq goy metallik': 'Göy',
    'aciq gumusu': 'Gümüşü',
    'aciq koric': 'Qəhvəyi',
    'aciq mavi': 'Göy',
    'aciq mavi metal': 'Göy',
    'aciq qehveyi': 'Qəhvəyi',
    'aciq qehveyi metallik': 'Qəhvəyi',
    'aciq qirmizi': 'Qırmızı',
    'aciq qirmizi metal': 'Qırmızı',
    'aciq qizili': 'Qızılı',
    'aciq qizili metallik': 'Qızılı',
    'aciq qum': 'Bej',
    'aciq sari': 'Sarı',
    'aciq tustu': 'Boz',
    'aciq yasemen': 'Bənövşəyi',
    'aciq yasil': 'Yaşıl',
    'aciq yasil metallik': 'Yaşıl',
    'afalina': 'Göy',
    'afalina metallik': 'Göy',
    'ag': 'Ağ',
    'ag bej': 'Ağ',
    'ag boz': 'Boz',
    'ag dam qara': 'Qara',
    'ag goy': 'Göy',
    'ag goy xett': 'Göy',
    'ag mavi': 'Göy',
    'ag metallik': 'Ağ',
    'ag mirvari': 'Ağ',
    'ag qirmizi yasil': 'Qırmızı',
    'ag qirmizi yasil xett': 'Qırmızı',
    'ag tustu': 'Boz',
    'ag yasil': 'Yaşıl',
    'akvamarin': 'Göy',
    'ala': 'Digər',
    'albali': 'Qırmızı',
    'albali metallik': 'Qırmızı',
    'albali perl': 'Qırmızı',
    'albali sedef': 'Qırmızı',
    'anqara': 'Boz',
    'apelsin': 'Narıncı',
    'araxis': 'Qırmızı',
    'atlantika': 'Göy',
    'avanturin': 'Yaşıl',
    'aysberq': 'Ağ',
    'badimcan': 'Bənövşəyi',
    'badimcan metallik': 'Bənövşəyi',
    'baltika': 'Göy',
    'banan': 'Sarı',
    'bayavi med': 'Digər',
    'bej': 'Bej',
    'bej gumusu': 'Gümüşü',
    'bej gumusu metallik': 'Gümüşü',
    'bej metallik': 'Bej',
    'bej yasil': 'Yaşıl',
    'bej yasil xett': 'Yaşıl',
    'bejiviy': 'Bej',
    'beliy noc': 'Ağ',
    'benovseyi': 'Bənövşəyi',
    'benovseyi metallik': 'Bənövşəyi',
    'beyaz gece': 'Ağ',
    'bordo': 'Qırmızı',
    'bosfor': 'Göy',
    'boz': 'Boz',
    'boz ag': 'Boz',
    'boz goy': 'Göy',
    'boz goy metallik': 'Göy',
    'boz gumusu': 'Gümüşü',
    'boz gumusu metallik': 'Gümüşü',
    'boz mavi': 'Göy',
    'boz mavi metallik': 'Göy',
    'boz metallik': 'Boz',
    'boz qara': 'Boz',
    'boz qehveyi': 'Boz',
    'boz qehveyi metallik': 'Boz',
    'boz qizili': 'Qızılı',
    'boz qizili metallik': 'Qızılı',
    'boz sedef': 'Boz',
    'boz yasemen': 'Boz',
    'boz yasemen metallik': 'Boz',
    'boz yasil': 'Yaşıl',
    'boz yasil metallik': 'Yaşıl',
    'brokatrot': 'Qırmızı',
    'brokatrot metallik': 'Qırmızı',
    'buran': 'Ağ',
    'burunc': 'Qızılı',
    'cehrayi': 'Çəhrayı',
    'delfin': 'Göy',
    'deniz dalgasi': 'Göy',
    'dinqo': 'Narıncı',
    'elektron': 'Göy',
    'elvan ag': 'Ağ',
    'elvan goy': 'Göy',
    'elvan qirmizi': 'Qırmızı',
    'elvan yasil': 'Yaşıl',
    'feya': 'Ağ',
    'fil sumuyu': 'Ağ',
    'firuzeyi': 'Digər',
    'firuzeyi metalik': 'Digər',
    'flora': 'Yaşıl',
    'gilenar': 'Qırmızı',
    'goy': 'Göy',
    'goy ag': 'Göy',
    'goy gece yarisi': 'Göy',
    'goy mat': 'Göy',
    'goy mavi': 'Göy',
    'goy metallik': 'Göy',
    'goy perl': 'Göy',
    'goy sari': 'Sarı',
    'goy valentin': 'Göy',
    'goy yasil': 'Yaşıl',
    'goy yasil metallik': 'Yaşıl',
    'gumusu': 'Gümüşü',
    'gumusu ag': 'Gümüşü',
    'gumusu bej': 'Gümüşü',
    'gumusu boz yasil': 'Gümüşü',
    'gumusu goy': 'Gümüşü',
    'gumusu goy fiolet': 'Gümüşü',
    'gumusu goy metallik': 'Gümüşü',
    'gumusu goy xet': 'Gümüşü',
    'gumusu goy yasil': 'Gümüşü',
    'gumusu mavi': 'Gümüşü',
    'gumusu metal': 'Gümüşü',
    'gumusu metal ag xett': 'Gümüşü',
    'gumusu metallik': 'Gümüşü',
    'gumusu metallik goy xet': 'Gümüşü',
    'gumusu perlamo': 'Gümüşü',
    'gumusu qara': 'Gümüşü',
    'gumusu qehveyi': 'Gümüşü',
    'gumusu qirmizi': 'Gümüşü',
    'gumusu qizili': 'Gümüşü',
    'gumusu qizili metallik': 'Gümüşü',
    'gumusu sari yasil': 'Gümüşü',
    'gumusu yasil': 'Gümüşü',
    'gumusu yasil mavi': 'Gümüşü',
    'gumusu yasil xett': 'Gümüşü',
    'gumusu yaxis': 'Gümüşü',
    'gumusu yaxis xett': 'Gümüşü',
    'iquana': 'Yaşıl',
    'iskra': 'Sarı',
    'jelt prim': 'Sarı',
    'kamis': 'Yaşıl',
    'kiparis': 'Yaşıl',
    'koral': 'Narıncı',
    'korrida': 'Qırmızı',
    'korrida metallik': 'Qırmızı',
    'korsika': 'Göy',
    'kremli': 'Ağ',
    'kul': 'Boz',
    'kules': 'Digər',
    'laguna': 'Göy',
    'laza': 'Göy',
    'liana yasil': 'Yaşıl',
    'liliya': 'Digər',
    'liloviy': 'Bənövşəyi',
    'limon': 'Sarı',
    'lipa yasil': 'Yaşıl',
    'lipo zelen': 'Yaşıl',
    'lotos': 'Ağ',
    'lotus': 'Ağ',
    'loza': 'Yaşıl',
    'malaxit': 'Yaşıl',
    'malina': 'Qırmızı',
    'manqo': 'Narıncı',
    'mavi': 'Göy',
    'mavi adriatika': 'Göy',
    'mavi goy': 'Göy',
    'mavi goy xett': 'Göy',
    'mavi gumusu': 'Gümüşü',
    'mavi gumusu metallik': 'Gümüşü',
    'mavi metallik': 'Göy',
    'maya': 'Sarı',
    'medeo': 'Göy',
    'metallik boz qara': 'Boz',
    'mimoza': 'Sarı',
    'miraj': 'Boz',
    'mudafie': 'Xaki',
    'murena': 'Göy',
    'nar': 'Qırmızı',
    'narinci': 'Narıncı',
    'narva': 'Qırmızı',
    'niaqara': 'Digər',
    'ofeliya': 'Ağ',
    'okean': 'Göy',
    'omeqa': 'Digər',
    'opal': 'Boz',
    'oranjeviy': 'Narıncı',
    'orta boz yas': 'Boz',
    'orta boz yas metallik': 'Boz',
    'osaka': 'Boz',
    'oxra': 'Qızılı',
    'oxra qizili': 'Qızılı',
    'paleviy': 'Bej',
    'papirus': 'Ağ',
    'parlaq ag': 'Ağ',
    'parlaq benovseyi': 'Bənövşəyi',
    'parlaq gumusu': 'Gümüşü',
    'parlaq gumusu metallik': 'Gümüşü',
    'parlaq qara': 'Qara',
    'parlaq qirmizi': 'Qırmızı',
    'parlaq sari': 'Sarı',
    'parlaq yasil': 'Yaşıl',
    'pesocni': 'Bej',
    'pitsunda': 'Yaşıl',
    'pixla': 'Yaşıl',
    'pixta': 'Yaşıl',
    'polad': 'Boz',
    'polevoy': 'Yaşıl',
    'primula': 'Sarı',
    'priz': 'Boz',
    'qamis': 'Yaşıl',
    'qar kralicasi': 'Ağ',
    'qara': 'Qara',
    'qara goy': 'Göy',
    'qara goy metallik': 'Göy',
    'qara metallik': 'Qara',
    'qara zumrud': 'Yaşıl',
    'qara zumrud metallik': 'Yaşıl',
    'qehveyi': 'Qəhvəyi',
    'qirmizi': 'Qırmızı',
    'qirmizi albali': 'Qırmızı',
    'qirmizi metallik': 'Qırmızı',
    'qirmizi nar': 'Qırmızı',
    'qirmizi narinci': 'Qırmızı',
    'qirmizi qehveyi': 'Qırmızı',
    'qizil boz': 'Qızılı',
    'qizil runo': 'Qızılı',
    'qizili': 'Qızılı',
    'qizili boz': 'Qızılı',
    'qizili metallik': 'Qızılı',
    'qizili oxra': 'Qızılı',
    'qobi': 'Xaki',
    'qolfstrim': 'Göy',
    'qolub adri': 'Göy',
    'qrafit': 'Boz',
    'qrafit metallik': 'Boz',
    'qranatoviy': 'Qırmızı',
    'qum': 'Bej',
    'qumlu': 'Bej',
    'rapsodiya': 'Bənövşəyi',
    'romans': 'Bənövşəyi',
    'rubin': 'Qırmızı',
    'sabalid': 'Qəhvəyi',
    'safari': 'Xaki',
    'salatoviy': 'Yaşıl',
    'sandal': 'Qəhvəyi',
    'sari': 'Sarı',
    'sari ag': 'Sarı',
    'sari goy': 'Sarı',
    'sari prim': 'Sarı',
    'sari primula': 'Sarı',
    'sari qirmizi': 'Qırmızı',
    'sarimtil ag': 'Ağ',
    'sehra': 'Xaki',
    'sehra boz': 'Xaki',
    'senej': 'Ağ',
    'sero beliy': 'Boz',
    'siklon': 'Boz',
    'silver': 'Gümüşü',
    'sitron': 'Sarı',
    'skat': 'Digər',
    'solgun bej': 'Bej',
    'solgun sari': 'Sarı',
    'sud': 'Ağ',
    'sv dimcat': 'Boz',
    'sv olivk': 'Yaşıl',
    'sv seriy': 'Boz',
    'sv zeleniy': 'Yaşıl',
    't koric': 'Qəhvəyi',
    't palidi': 'Qəhvəyi',
    'tavriya': 'Yaşıl',
    'terrokati': 'Narıncı',
    'tornado': 'Boz',
    'tund ag': 'Ağ',
    'tund albali': 'Qırmızı',
    'tund albali metallik': 'Qırmızı',
    'tund bej': 'Bej',
    'tund benovseyi': 'Bənövşəyi',
    'tund bordo': 'Qırmızı',
    'tund boz': 'Boz',
    'tund boz metallik': 'Boz',
    'tund boz yasil': 'Yaşıl',
    'tund dalga': 'Göy',
    'tund goy': 'Göy',
    'tund goy metallik': 'Göy',
    'tund goy sedef': 'Göy',
    'tund gumusu': 'Gümüşü',
    'tund gumusu metallik': 'Gümüşü',
    'tund mavi': 'Göy',
    'tund mavi metallik': 'Göy',
    'tund nar': 'Qırmızı',
    'tund nar metallik': 'Qırmızı',
    'tund palidi': 'Qəhvəyi',
    'tund qehveyi': 'Qəhvəyi',
    'tund qirmizi': 'Qırmızı',
    'tund qirmizi cehrayi': 'Qırmızı',
    'tund qirmizi nar': 'Qırmızı',
    'tund sud': 'Ağ',
    'tund sudlu': 'Digər',
    'tund yasemen': 'Bənövşəyi',
    'tund yasil': 'Yaşıl',
    'tund yasil metallik': 'Yaşıl',
    'tund yasil sedef': 'Yaşıl',
    'tund zogali': 'Qırmızı',
    'tustu': 'Boz',
    'tutun': 'Qəhvəyi',
    'valentina': 'Qırmızı',
    'valyuta': 'Yaşıl',
    'vasilik': 'Göy',
    'vasilkoviy': 'Göy',
    'visnoviy': 'Qırmızı',
    'xaki': 'Xaki',
    'yar sari': 'Sarı',
    'yar zeleni': 'Yaşıl',
    'yark beliy': 'Ağ',
    'yas asfalt': 'Boz',
    'yasemen': 'Bənövşəyi',
    'yasemen metallik': 'Bənövşəyi',
    'yasil': 'Yaşıl',
    'yasil ag': 'Yaşıl',
    'yasil ag xett': 'Yaşıl',
    'yasil bag': 'Yaşıl',
    'yasil bej': 'Yaşıl',
    'yasil gumusu': 'Gümüşü',
    'yasil gumusu metallik': 'Gümüşü',
    'yasil metal': 'Yaşıl',
    'yasil metallik': 'Yaşıl',
    'yasil murena': 'Yaşıl',
    'yasil perlam': 'Yaşıl',
    'yasil sari': 'Sarı',
    'zarya': 'Qırmızı',
    'zeytun': 'Yaşıl',
    'zumrud': 'Yaşıl',
    'zumrud metallik': 'Yaşıl',
}

def normalize_color(c):
    """
    Rəngi standart qrupa salır.
    Tanınmayan bütün yeni/kirli rənglər avtomatik 'Digər' olur.
    Substring axtarışı yoxdur; məsələn 'niaqara' artıq 'Qara' sayılmır.
    """
    key = _basic_key(c)
    if not key:
        return "Digər"

    if key in COLOR_MAPPING:
        return COLOR_MAPPING[key]

    key2 = _strip_descriptors(key)
    if key2 in COLOR_MAPPING:
        return COLOR_MAPPING[key2]

    return "Digər"
